Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 82, in open
  File "serial\serialwin32.pyo", line 202, in _reconfigurePort
ValueError: Cannot configure port, some setting was wrong. Original message: WindowsError(2, 'The system cannot find the file specified.')

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 82, in open
  File "serial\serialwin32.pyo", line 202, in _reconfigurePort
ValueError: Cannot configure port, some setting was wrong. Original message: WindowsError(2, 'The system cannot find the file specified.')

